### ISSUE TITLE
tty.c: siginterrupt is deprecated

### ISSUE THREAD

**Issue by RoastVeg** [troglobit/mg#10]
Warning produced by gcc 10.2.0 on Linux. I am unaware if the proposed change by the compiler is portable to other systems.

```
tty.c: In function ‘ttinit’:
tty.c:73:2: warning: ‘siginterrupt’ is deprecated: Use sigaction with SA_RESTART instead [-Wdeprecated-declarations]
   73 |  siginterrupt(SIGWINCH, 1);
      |  ^~~~~~~~~~~~
In file included from tty.c:33:
/usr/include/signal.h:311:12: note: declared here
  311 | extern int siginterrupt (int __sig, int __interrupt) __THROW
      |            ^~~~~~~~~~~~
```

**Comment by troglobit** [comment]
OK, I'll have a look at it in the next release cycle.  Thank you for taking the time to report this!

**Comment by troglobit** [comment]
Just tried to reproduce on one of my bleeding edge Debian systems with GCC 10.2.1 ... no luck.  Did you use any special CFLAGS or such to get this?  The default flags for mg are `-W -Wall -Wextra`, which usually triggers lots of warnings, but I've fixed all I can see. 

(Sure we need to address siginterrupt() deprecation regardless, I'm just curious why I cannot reproduce the same result as you)

**Comment by RoastVeg** [comment]
What version of libc are you building against? `siginterrupt` seems to have been marked as of [glibc v2.32](https://sourceware.org/pipermail/libc-announce/2020/000029.html), which is what I am running.

**Comment by troglobit** [comment]
Aha, that's it, thanks!  My Debian machine was still on v2.31.  I'll rebuild on Buildroot instead. Cheers!
