### ISSUE TITLE
Errors on cygwin

### ISSUE THREAD

**Issue by xpusostomos** [troglobit/mg#15]
On cygwin, with
./configure
make

I get this error.

c/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-autoexec.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-cmode.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-grep.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-cscope.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-tags.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-dired.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-re_search.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: mg-ansi.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: ../lib/fparseln.o:/c/Users/chris/Downloads/mg-3.4/src/./def.h:653: multiple definition of `hlp'; mg-basic.o:/c/Users/chris/Downloads/mg-3.4/src/def.h:653: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:500: mg.exe] Error 1

Now it's been a while since I coded C, but in def.h it has...

const char * hlp;

Seems like a no-no to declare a variable in a header file to me. Anyway I changed this to..

extern char * hlp;

and then it compiled and linked

But the other problem is, when I start the editor, nothing happens until I press any key. So if I type
src/mg foo [enter]

Nothing at all happens until I press some other key... like for example, pressing enter a second time. Or just pressing any key.

**Comment by troglobit** [comment]
Hi! 

This is fixed on the latest master branch, commit 29c83c9, which I've been dragging my feet to release.  It's pending a sync with the "upstream" OpenBSD sources.  I just tested master on an old Windows 10 install with Cygwin, and it works fine there.  

Just remember, when building from GIT sources, you need to run ./autogen.sh first. More info in the README.
