### ISSUE TITLE
Build on Ubuntu 16.04

### ISSUE THREAD

**Issue by ThomasHornschuh** [troglobit/mg#2]
To build on ubuntu libncurses5-dev is required. Maybe you can add this to the readme.

**Comment by troglobit** [comment]
Hi,

the README currently states the following in the section Building:

> The project is almost completely self hosting, you need a 3rd party termcap library, or ncurses,
> to provide terminal manipulation APIs like setupterm(), tgoto(), and tputs().
>
> On Debian/Ubuntu based systems libtinfo-dev can be used:
> 
> `sudo apt install libtinfo-dev`

**Comment by ThomasHornschuh** [comment]
Hi,
of course I have first tried it with libtinfo-dev. But it didn't work, at least on my system. During configure I got an error message that term.h cannot be found. With installing libncurses5-dev the error disappeared

**Comment by troglobit** [comment]
It seems Debian (and thus also Ubuntu) over time have changed the packaging of ncurses (which provides libtinfo on Linux systems).  Sometime between Ubuntu 16.04 and 18.10, however, libtinfo-dev was updated to depend on libncurses5-dev.  

OK, I'll add something to the README. Thanks for the heads-up!
