### ISSUE TITLE
feature: press f5 to insert timestamp in user format

### ISSUE THREAD

**Issue by rchou** [troglobit/mg#20]
Hi, 
Love mg. had this feature in emacs init, felt very useful to quickly add a timestamp in file, journal or code. Was used to it in an old windows text editor. Can we add this to mg please? I do see an mg command of 'display-time-mode' that does something different. mg(osx) doesn't recognise f1-f4, and thinks f5-f10 is ~. Raised it with ibara/mg a few months back, still untouched. In emacs init it was like this bound to [f5], (insert (format-time-string "%Y %b %d %p %-I\n"))) ;2020 Sep 02 PM 10 24

Also, hboetes mg has a release on 2022 Nov 12, that may have something useful to merge.
Thanks,
Rahul

**Comment by troglobit** [comment]
I package only upstream OpenBSD mg features. I don't do features on request. If you like you can submit a pull-request with your feature, but I'll only merge it at my own discretion. I.e., if it's generic enough to be useful to others.  

Have you seen the upstream efforts to add lisp-like scripting to mg?  Maybe that can be used to implement your feature.
