### ISSUE TITLE
highlight selected region

### ISSUE THREAD

**Issue by varna9000** [troglobit/mg#24]
I've compiled mg for Mac but selecting a region (eg. C-SPC, C-e) doesn't highlight the text.
Is this normal? On normal full Emacs it does highlight it.

**Comment by troglobit** [comment]
Yes, this is normal.

**Comment by posguy99** [comment]
@varna9000 If that is important to you, you might look at [qemacs](https://github.com/qemacs/qemacs).

**Comment by troglobit** [comment]
Yup. There are lots of alternatives out there. And we are of course also interested in pull requests (contributions) for implementing a visual mark mode like GNU Emacs.

**Comment by varna9000** [comment]
Thanks. I was just asking, because I think the expected behaviour would be the get some visual feedback of the `select` action. It seems qemacs has this feature.
