### ISSUE TITLE
Please remove annoying message when saving

### ISSUE THREAD

**Issue by blakemcbride** [troglobit/mg#25]
When you save a file without a terminating linefeed the system says:  ```No newline at end of file, add one? (y or n)```  This is very annoying.  No other editor I know does this.  Please remove this!

There are a 1000 other checks your editor could perform and warn me about at save time.  Please don't!

**Comment by troglobit** [comment]
Hi Blake, this is a feature of the OpenBSD upstream Mg that I too have been annoyed with on multiple occasions.  I can of course remove it in my fork, but are you sure you are using my fork?

**Comment by troglobit** [comment]
Plan (notes to self):

 - Add `require-final-newline` with at least three settings: `ask`, `T`, `nil`
 - Set `require-final-newline` to `nil` by default in our fork
 - Update man page

**Comment by blakemcbride** [comment]
Hi.  Yes, I compiled from GitHub source.  Thanks!

**Comment by blakemcbride** [comment]
Thank you!
