### ISSUE TITLE
Possible to delete a region?

### ISSUE THREAD

**Issue by smahm006** [troglobit/mg#26]
Hello thank you for this editor,

I am wondering if there are two things possible:
1. Selecting region will show a highlight of the region similar to transient-mark-mode.
2. Can you delete a whole region by selecting it and pressing backspace?

**Comment by troglobit** [comment]
1. See #24
2. No

Both of these are common questions and come up at times even in the upstream OpenBSD distribution of Mg. Fairly easy to add but nobody has stepped up yet.

**Comment by smahm006** [comment]
Ok thank you, I will try to take a crack at it and if I can get anywhere I will raise a PR.
