### ISSUE TITLE
config file examples

### ISSUE THREAD

**Issue by CDitzel** [troglobit/mg#27]
Can you share some examples of .mg config files please?

There is nothing non the web unfortunately

**Comment by CDitzel** [comment]
thanks but I am more interested in what setting are available in general, in other words: what can be customized and to what extend?

Also, I noticed that dired-up-directory is absent from your take on mg. Is that on purpose?

**Comment by troglobit** [comment]
Well, what's available is documented in the man page.

I track the upstream OpenBSD Mg, blend it with my own extensions & fixes.  I try to synchronize with their changes and additions when I can, but the `dired-up-directory` was [added in the beginning of June](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/mg/dired.c) and I've not had the time yet to pull it in.  Simple as that.

**Comment by CDitzel** [comment]
thanks for the explanation <3

**Comment by CDitzel** [comment]
sir, yes sir!
