### ISSUE TITLE
grep not working

### ISSUE THREAD

**Issue by CDitzel** [troglobit/mg#28]
I cant seem to get grep to work, neither on the official package nor this repository. Is this issue known?

**Comment by troglobit** [comment]
Please, when reporting an issue, include the steps you took to trigger the problem.

FWIW, it works just fine here (equally non-descriptive).

**Comment by CDitzel** [comment]
![image](https://github.com/user-attachments/assets/8147ee10-5b9c-4143-bab6-70a618d61d49)

looks like this, am I missing somesthing here?

**Comment by troglobit** [comment]
Looks like this for me:

![mg-grep](https://github.com/user-attachments/assets/365ae334-af9e-4544-a7b9-ecee5e0a9945)

Maybe try supplying a file argument to grep?

**Comment by CDitzel** [comment]
yes I did, did not know I had to, thanks
