### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by xpusostomos** [troglobit/mg#5]
The build instructions say to run ./configure, but there is no configure. I thought I'd try installing automake to see if that got me any further, but it didn't seem to, at least on cygwin.

**Comment by troglobit** [comment]
How did you download mg?  There are *versioned* tarballs and zip files in the releases page that include the generated configure script, so you should not need automake et al as an end-user.   However, GitHub creates "Source Archive" download links which are only snapshots of GIT, which do not include the generated files.

If you want to build from GIT directly, i.e. you have run `git clone ...`, then you can run the ./autogen.sh script to generate the configure script and Makefile.in files. This requires a few more tools, like autoconf.

**Comment by xpusostomos** [comment]
Ahh ok, I didn't know about the releases page. I did a git clone which I thought is the default way of acquiring code you are expected to build yourself.

**Comment by troglobit** [comment]
Depends on the project. Many maintainers are sloppy and don't even do a `git tag ...`, but I try to set a higher standard. I am however picky with not including generated files in GIT (like binaries, they don't belong in source control, imho).

I'll include a section in the README to help clarify this.

**Comment by troglobit** [comment]
It seems I've already done so https://github.com/troglobit/mg/blame/master/README.md#L78 ... there's even a mention of using the latest release https://github.com/troglobit/mg/blame/master/README.md#L16
