### ISSUE TITLE
Compile errors then fail.

### ISSUE THREAD

**Issue by Unixware** [troglobit/mg#9]
I can compile the 3.4 under CentOS 7 but not Debian Testing .
Lots of errors about **multiple definition of `hlp'** , thanks

`
/usr/bin/ld: mg-bell.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-buffer.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-cinfo.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-dir.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-display.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-echo.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-extend.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-file.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-fileio.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-funmap.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-help.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-interpreter.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-kbd.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-keymap.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-line.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-macro.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-main.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-match.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-modes.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-paragraph.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-region.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-search.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-spawn.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-tty.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-ttyio.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-ttykbd.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-undo.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-util.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-version.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-window.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-word.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-yank.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-extensions.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-autoexec.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-cmode.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-grep.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-cscope.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-tags.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-dired.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: mg-re_search.o:/media/chris/data/mg-3.4/src/def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
/usr/bin/ld: ../lib/fparseln.o:/media/chris/data/mg-3.4/src/./def.h:653: multiple definition of `hlp'; mg-basic.o:/media/chris/data/mg-3.4/src/def.h:653: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:500: mg] Error 1
make[2]: Leaving directory '/media/chris/data/mg-3.4/src'
make[1]: *** [Makefile:398: all] Error 2
make[1]: Leaving directory '/media/chris/data/mg-3.4/src'
make: *** [Makefile:451: all-recursive] Error 1

`

**Comment by troglobit** [comment]
Sorry about that, I forgot to test with gcc-10 before releasing. This is fixed in the last master, found by the Buildroot project as well. 

Use a patch from 29c83c917 to get just what you need.
